[package]
name = "axum_typed_multipart_macros"
description = "Macros for axum_typed_multipart."
license = "MIT"
repository = "https://github.com/murar8/axum_typed_multipart"
authors = ["Lorenzo Murarotto <lnzmrr@gmail.com>"]
edition = "2021"
version = "0.5.0"

[lib]
proc_macro = true

[dependencies]
darling = "0.20.1"
proc-macro-error = "1.0.4"
quote = "1.0.28"
syn = "2.0.18"
