[package]
name = "axum_typed_multipart_macros"
description = "Macros for axum_typed_multipart."
license = "MIT"
repository = "https://github.com/murar8/axum_typed_multipart"
authors = ["Lorenzo Murarotto <lnzmrr@gmail.com>"]
edition = "2021"
version = "0.10.1"


[lib]
proc_macro = true


[dependencies]
darling = "0.20.3"
proc-macro-error = "1.0.4"
quote = "1.0.32"
syn = "2.0.28"
ubyte = "0.10.3"
heck = "0.4.1"


[dev-dependencies]
axum = { version = "0.6.20", features = ["multipart"] }
axum_typed_multipart = { path = ".." }
axum-test-helper = "0.3.0"
reqwest = "0.11.18"
tokio = { version = "1.30.0" }
